version: '3.8'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: HE_horse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups

  backup:
    image: postgres:17
    volumes:
      - postgres_backups:/backups
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: your_password
      PGDATABASE: HE_horse_db
      BACKUP_DIR: /backups
    entrypoint: |
      sh -c 'while true; do
        pg_dump -h db -U $$PGUSER -F c -b -v -f "/backups/HE_horse_db_$$(date +%Y_%m_%d_%H_%M_%S).backup" $$PGDATABASE
        find /backups -name "HE_horse_db_*.backup" -mtime +7 -delete
        sleep 86400
      done'

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: horse_tracking
      POSTGRES_USER: horse_tracker_app
      POSTGRES_PASSWORD: silverback_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=horse_tracker_app
      - DB_PASSWORD=silverback_secure_password
      - DB_NAME=horse_tracking
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080/api

volumes:
  postgres_data:
    driver: local
  postgres_backups:
